name: aw-portfolio

on:
  push:
    branches:
      - main


jobs:
  detect-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            backend : 
              - 'aw-portfoiio-api/**'
            frontend : 
              - 'aw-portfoiio-front/**'

    outputs:
      backend: ${{ steps.changes.outputs.backend }}
      frontend: ${{ steps.changes.outputs.frontend }}

  build-backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: gradle 권한 부여 및 빌드
        run: |
          cd aw-portfoiio-api
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: 빌드된 파일 이름 변경하기
        run: |
         cd aw-portfoiio-api
         mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: SCP로 EC2에 빌드된 파일 전송하기
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: aw-portfoiio-api/project.jar
          target: /home/ubuntu/spring-server/tobe
          strip_components: 1

      - name: ssh 접속
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          port: 22
          script: |
            rm -rf /home/ubuntu/spring-server/target
            mkdir -p /home/ubuntu/spring-server/target
            mv /home/ubuntu/spring-server/tobe/project.jar /home/ubuntu/spring-server/target
            cd /home/ubuntu/spring-server/target
            sudo fuser -k -n tcp 8080 || true
            DB_USERNAME='${{ secrets.DB_USERNAME }}' \
            DB_PASSWORD='${{ secrets.DB_PASSWORD }}' \
            DB_URL='${{ secrets.DB_URL }}' \
            DB_PORT='${{ secrets.DB_PORT }}' \
            AWS_ACCESS_KEY='${{ secrets.AWS_ACCESS_KEY }}' \
            AWS_SECRET_KEY='${{ secrets.AWS_SECRET_KEY }}' \
            AWS_REGION='${{ secrets.AWS_REGION }}' \
            AWS_BUCKET='${{ secrets.AWS_BUCKET }}' \
            nohup java \
            -Dspring.profiles.active=real \
            -Duser.timezone=Asia/Seoul \
            -jar project.jar > /dev/null 2>&1 &
            rm -rf /home/ubuntu/spring-server/tobe

  build-frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Node설치
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: 의존성 설치
        run: |
          cd aw-portfoiio-front
          npm i

      - name: 빌드
        run: |
          cd aw-portfoiio-front
          NODE_ENV=production DATABASE_URL=${{ secrets.DATABASE_URL }} npm run build

      - name: 압축하기
        run: |
          cd aw-portfoiio-front
          tar -czvf project.tar.gz .next package.json package-lock.json public prisma

      - name: SCP로 EC2에 빌드된 파일 전송하기
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: aw-portfoiio-front/project.tar.gz
          target: /home/ubuntu/nextjs-server/tobe
          strip_components: 1

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            rm -rf /home/ubuntu/nextjs-server/current
            mkdir -p /home/ubuntu/nextjs-server/current
            mv /home/ubuntu/nextjs-server/tobe/project.tar.gz \
            /home/ubuntu/nextjs-server/current/project.tar.gz
            cd /home/ubuntu/nextjs-server/current
            tar -xvf project.tar.gz
            npm i
            pm2 delete next-server || true
            DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            pm2 start npm --name next-server -- start
            pm2 save
